# Copy to database.properties and adjust. database.properties is gitignored.
jdbc.url=jdbc:mysql://localhost:3306/wedding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
jdbc.username=root
jdbc.password=kavii@14_

#Jasmi
jdbc.url=jdbc:mysql://localhost:3306/wedding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
jdbc.username=root
jdbc.password=jasmi

